ModernOutfit/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('register/', user_views.register,name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

products/urls.py
from products import views
from django.urls import path

app_name = 'products'

urlpatterns = [

    path('', views.index, name='index'),
    path('<int:item_id>/', views.details, name='details'),
    path('add/', views.create_item, name='create_item'),
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/', views.delete_item, name='delete_item'),

]

products/models.py
from django.db import models

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name

    item_name = models.CharField(max_length=200)
    item_describe = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://schulershoes-magento.s3.amazonaws.com/pub/media/catalog/product/placeholder/default/PLACEHOLDER.jpg")

users/models.py
from django.db import models

# Create your models here.

products/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name", "item_describe", "item_price", "item_image"]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Here is the form of Register which we can modify our fields

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

products/views.py
from django.shortcuts import render, redirect
from .models import Item
from django.template import loader
from .forms import ItemForm
# Create your views here.

def index(request):

    item_list = Item.objects.all()
    context = {

        'item_list': item_list
    }

    return render(request, 'products/index.html', context)


#def item(request):
#   return HttpResponse("this item is here now")


def details(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item
    }
    return render(request, 'products/details.html', context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('products:index')
    return render(request, 'products/item-form.html', {'form':form})


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('products:index')
    
    return render(request, 'products/item-form.html', {'form':form, 'item':item})


def delete_item(request, id):
    item = Item.objects.get(id=id)
    
    if request.method == 'POST':
        item.delete()
        return redirect('products:index')
    return render(request, 'products/item-delete.html', {'item': item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm

# Here are the views which take a request and return a response.

def register(request):
    """ a view that responsible fro Registration of users """

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, Your account is created')
            return redirect('products:index')

    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form':form})

products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'products/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark ps-4 pe-5 d-flex justify-content-center position-relative">
        <a href="#" class="navbar-brand text-primary">ModernOutfit</a>
        
        <div class="navbar text-light">
            {% if user.is_superuser %}
                <a href="{% url 'logout' %}" class="nav-item nav-link ps-3 pe-4">logout</a>
                <a href="{% url 'products:create_item' %}" class="nav-item nav-link pe-3 " >Add Item</a>
                <a href="#" class="nav-item nav-link ps-3 pe-4">Delet Item</a>
                <a href="#" class="nav-item nav-link ps-3">View Item</a>
            
            {% elif user.is_authenticated %}
                <a href="{% url 'logout' %}" class="nav-item nav-link ps-3 pe-4">logout</a>
                <a href="#" class="nav-item nav-link ps-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="20" fill="currentColor" class="bi bi-bag-heart" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5Zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0ZM14 14V5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1ZM8 7.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z"/>
                    </svg>
                </a>
            {% else %}
                <a href="{% url 'login' %}" class="nav-item nav-link ps-3">login</a>
            {% endif %}
        </div>

        


    </nav>

    {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}}">
                    {{message}}
                </div>
                
            {% endfor %}
        {% endif %}


    {% block body %}

    {% endblock %}
    
</body>

</html>

products/templates/products/details.html
{% extends 'products/base.html' %}
{% block body %}


    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img height="300px" src="{{ item.item_image }}" class=""/>

            </div>
            
            <div class="col-md-6">
                <h1>{{ item.item_name }}</h1>
                <h2>{{ item.item_describe }}</h2>
                <h3>${{ item.item_price }}</h3>
                {% if user.is_superuser %}
                    <a href="{% url 'products:delete_item' item.id %}">Delete</a>
                {% endif %}
            </div>

        </div>

    </div>


    
{% endblock %}

products/templates/products/index.html
{% extends 'products/base.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    </head>

    <body>
        
        {% block body %}
        <main class="mt-5 d-flex justify-content-center">
            <div class="d-flex flex-column gap-5">

                {% for item in item_list %}
                
                <div class="row bg-dark-subtle py-2 rounded-2">
                    
                    <div class="col-md-3 offset-md-2">
                        <img class="" height="180px" src="{{ item.item_image }}">
                    </div>
                    
                    <div class="col-md-4">
                        <h3> {{ item.item_name }} </h3>
                        <h5> {{ item.item_describe }} </h5>
                        <h6> ${{ item.item_price }} </h6>
                    </div>
                    
                    <div class="col-md-2">
                        <a href="{% url 'products:details' item.id %}" class="btn btn-success">Details</a>
                    </div>
                            
                </div>
                
                {% endfor %}      
            </div>
        </main>
        {% endblock %}
                    
            
            
    </body>
        
</html>

products/templates/products/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

products/templates/products/item-form.html
{% extends 'products/base.html' %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>

</form>

users/templates/users/logout.html
<h1>You loged out</h1>

users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">SignUp</button>


</form>